import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import teams from "../src/data/teams.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const statsPath = path.join(root, "src/data/matchStatsCompact.json");
const outputPath = path.join(root, "src/data/maps.js");

if (!fs.existsSync(statsPath)) {
  throw new Error(`Stats file not found: ${statsPath}`);
}

const stats = JSON.parse(fs.readFileSync(statsPath, "utf8"));
const byId = new Map(teams.filter((team) => team.faceitTeamId).map((team) => [team.faceitTeamId, team]));
const normalize = (value = "") => String(value).trim().replace(/\s+/g, "").toLowerCase();
const byName = new Map(teams.map((team) => [normalize(team.name), team]));
const totals = new Map();

function cleanMapName(value) {
  const raw = String(value || "").trim();
  if (!raw) return null;
  return raw
    .replace(/^de_/i, "")
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

function resolveTeam(item) {
  return byId.get(item?.teamId) || byName.get(normalize(item?.teamName)) || null;
}

for (const match of Object.values(stats)) {
  const mapName = cleanMapName(match?.map);
  const matchTeams = Array.isArray(match?.teams) ? match.teams : [];
  if (!mapName || matchTeams.length < 2) continue;

  const scores = matchTeams.map((item) => Number(item?.score));
  if (scores.some((score) => !Number.isFinite(score))) continue;
  const maxScore = Math.max(...scores);
  const winnerCount = scores.filter((score) => score === maxScore).length;

  matchTeams.forEach((item, index) => {
    const local = resolveTeam(item);
    if (!local) return;

    if (!totals.has(local.slug)) totals.set(local.slug, new Map());
    const mapTotals = totals.get(local.slug);
    const current = mapTotals.get(mapName) || { played: 0, wins: 0 };
    current.played += 1;
    if (winnerCount === 1 && scores[index] === maxScore) current.wins += 1;
    mapTotals.set(mapName, current);
  });
}

const result = {};
for (const team of teams) {
  const mapTotals = totals.get(team.slug);
  if (!mapTotals) continue;

  result[team.slug] = [...mapTotals.entries()]
    .map(([name, value]) => ({
      name,
      winrate: Number(((value.wins / value.played) * 100).toFixed(1)),
      played: value.played,
    }))
    .sort((a, b) => b.played - a.played || b.winrate - a.winrate || a.name.localeCompare(b.name));
}

const output = `// Generated by scripts/generateMaps.js. Do not edit manually.\nconst maps = ${JSON.stringify(result, null, 2)};\n\nexport default maps;\n`;
fs.writeFileSync(outputPath, output);

console.log(`Generated map stats for ${Object.keys(result).length} teams from ${Object.keys(stats).length} match maps.`);
